spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/agonaBC
    username: postgres
    password: 26042004
    driverClassName: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
logging:
  level:
    org:
      springframework:
        security: DEBUG